classes/EasterEgg.py, functions.py
=> Refactoring and mlezioni

data/json/professori.json
=> add prof cristina milazzo

README.md, functions.py
Check commits log for more clarifications
=> Various fix

data/json/lezioni.json, functions.py, module/scraperesami.py, module/scraperorario.py
Fixed identation, scrapeorario path problem and scrapesami problem with third appeal of first session
=> Minor bug fixes

data/json/professori.json, functions.py
If a message exceeds 4096 ascii characters, Telegram will trim it.
mandaMessaggio() function resolve this problem.
=> added mandaMessaggio() function that splits long messages

README.md, requirements.txt
The installation through pip is more convenient and also works on Windows.
=> Moved "Beautiful Soup 4" requirement from "system" to "pip"

README.md, data/markdown/cloud.md, data/markdown/contributors.md, functions.py, main.py
Need to change the cloud.md text to better explain the differences between the different cloud folders
=> Added /cloud command that links all DMI cloud folders

functions.py, main.py, module/gitlab.py, module/lezioni.py, module/scraper_professors.py
=> Removed warnings, still some things to fix

.gitignore, README.md, config/settings.yaml.dist, data/DMI_DB.sql, functions.py, main.py, module/easter_egg_func.py, module/gitlab.py, module/shared.py
- refactored callbackqueryhandler system
- removed useless functions
- fixed /cloud markup using button (/help -> cloud cloud)
- improved Esami, Lezioni, Aulario buttons (/help)
- removed old "news system" and "mensa" remaining code
- removed shorturl and forum*() functions
- updated .gitignore
- updated README.md
Close #64
=> Refactored callbackqueryhandler, fixed minor bugs,removed useless functions, close #64

functions.py, main.py, module/regolamento_didattico.py
Ritorna un menu da dove scegliere il regolamento didattico in base al proprio anno d' immatricolazione
=> Aggiunto il comando /regolamentodidattico 

functions.py, module/scraper_exams.py, module/scraper_lessons.py, module/shared.py, requirements.txt
Exams and Lessons scraping based on current date.
=> Close issue #68

functions.py
Year code is going to switch after aaaa/12/20
=> Changed hard coded string into InlineKeyboardButton for exams dates

functions.py, main.py, module/esami.py, module/scraper_exams.py, module/shared.py
scraper_exams: le stringhe ottenute dallo scraping vengono sottoposte ad un .replace("\"", "'"), per evitare errori nella formazione della query. Aggiunto un piccolo blocco try-except
main - functions: modificata la funzione .informative_callback, così che non abbia bisogno del parametro aggiuntivo ma se lo procuri dal parametro update
shared: aggiunto il parametro encoding="utf8" all'apertura del file. Non so se riguarda solo me, ma il fatto che mancasse ha creato alcuni problemi
esami: nella funzione .esami_condition, sotituito il parametro *session con session = False per maggiore chiarezza
=> fix: scraper_exams   refactor: main, functions, shared, esami

module/esami.py
Ho fatto varie prove con docker, e sembrerebbe che il problema sia che nell'implementazione locale di sqlite3 
`Where true `
non piaccia all'interno di una query. Quindi mi sono scervellato per trovare un'alternative
=> fix: true is not a creative color

data/markdown/cloud.md, functions.py
maggiore leggibilità: invece di una tupla, la return value della funzione "get_esami_text_InlineKeyboard" viene spacchettata nelle rispettive variabili
aggiornato il link all'aulario: il link ora porta al nuovo aulario  [closes #78]
=> refactor: maggiore leggibilità   fix: aggiornato il link all'aulario 

README.md, classes/EasterEgg.py, data/markdown/contributors.md, module/easter_egg_func.py
Fix error caused by config_map dict on `module` file and created ester egg element choosing from a list instead of using if-elif-else.
[Resolved #86 ]
=> Easter egg exception

module/gitlab.py
fix https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/93
=> fix(gitlab): integration gitlab and PDF with LFS

functions.py, module/esami.py
Nella formazione della query, più precisamente nella clausola WHERE, la stringa che contiene l'insegnamento inserito dall'utente viene sanificata utilizzando la parametrizzazione fornita da "sqlite3" [closes #95 ]
Devo ringraziare chi si è messo a spammare insegnamenti dai nomi che curiosamente  ricordavano una query SQL per avermi insegnato l'importanza di sanificare ogni input che potrebbe essere un portatore non troppo sano di qualche malattia
=> fix(esami): sanificazione  della query

data/markdown/biblioteca.md
=> Sistemati i caps dei giorni feriali

functions.py, module/lezioni.py, module/scraper_lessons.py
The scraper was not working properly since the structure of the lesson's page has changed, adding one more <td> for Microsoft Teams codes.
Also fixed some lines on lezioni.py (some values were not correctly compared/inserted)
=> Fixed scraper_lessons and /lezioni command not working properly.

data/markdown/contributors.md, data/markdown/rappresentanti_matematica.md
Fixato il markdown dei file contributors.md e rappresentanti_matematica.md.
=> fix(markdown): '\' necessario prima del carattere '_'

module/stats.py, requirements.txt
Ora la lista di comandi è ordinata secondo il numero di volte che un comando è stato utilizzato, e ci sono 2 info aggiuntive, cioè il totale degli utilizzi e la media per comando [closes #115].
Il risultato è il seguente
Non sono sicuro sul come realizzare il graph: oltre a dover usare un'apposita libreria, penso che un grafico (a torta o a barre) sarebbe un po' poco leggibile perché ci sono tante labels (comandi). Se avete in mente qualcosa suggerite
=> improve: /stat and /stat_tot commands

data/markdown/help.md, main.py, module/help.py, module/shared.py, module/utils/keyboard_utils.py
improved reusability of the constants, now it's easy to edit the buttons from only one file (shared.py)
moreover, I improved the description of the command aulario
close https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/126
=> refact(aulario-keyboard): minor refactoring

data/markdown/professori.md, module/help.py
=> Add info professori button on help menu

module/professori.py
Issue example:
Ruolo: Ricercatore
Cognome: Di
Nome: Super Mario
Solution:
Ruolo: Ricercatore
Nome: Mario Di Super
=> Fix prof output nome and cognome

.dockerignore, Dockerfile, README.md
- use latest python image
- don't use ARG for TOKEN
- add dockerignore
- update readme(docker section)
=> feat(docker): update dockerfile

data/DMI_DB.sql, module/commands/professori.py, module/data/professor.py
close https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/157
=> fix(prof): fix issue #157

data/markdown/ricevimenti.md, data/markdown/trasporto_urbano_unict.md, main.py
Closes https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/143
Closes https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/142
=> feat: add 2 new commands

module/commands/regolamento_didattico.py, tests/test_bot.py, tests/test_bot.py2
=> Fix "Regolamento didattico" for Maths classes

module/callback_handlers.py, module/commands/help.py
=> feat: shorter help command

module/callback_handlers.py, module/commands/help.py
=> feat: Back to the menu

.gitignore, module/callback_handlers.py
Closes #121 
_This PR will change the behavior of every keyboard menu that makes use of the exit_hanlder._
=> Add on close deletion for onkeyboard menu

.github/workflows/telegram-bot.yml, CONTRIBUTORS.md, README.md, data/markdown/contributors.md, requirements.txt, requirements_dev.txt
This fix github actions build and deploy issue
=> chore: update dependencies

data/markdown/cloud.md, module/callback_handlers.py, module/commands/drive_contribute.py
=> feat: improve drive_contribute command, closes #194, #192

module/commands/regolamento_didattico.py
closes https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/189
=> feat: back to menu button in "regolamento didattico"

main.py, module/commands/regolamento_didattico.py
/regolamentodidattico command now call a menu with "Informatica" and "Matematica" options that call a submenu with "Triennale" and "Magistrale" options. On this, they call a list of documents organized according to user choice.
=> feat: /regolamentodidattico: added a more organized menu

module/commands/aulario.py, module/data/vars.py
=> Added a "vars.py" file that will include all text vars from all modules

CONTRIBUTORS.md, module/commands/drive_contribute.py, module/commands/esami.py, module/commands/gdrive.py, module/commands/help.py, module/commands/lezioni.py, module/commands/regolamento_didattico.py, module/commands/report.py, module/commands/stats.py, module/data/vars.py
=> Updated "vars.py" and "CONTRIBUTORS.md"

module/callback_handlers.py, module/commands/esami.py, module/commands/help.py, module/commands/lezioni.py, module/utils/multi_lang_utils.py
Closes #208 
This PR is just a workaround for the current issue related to the language_code obfuscation.
To fix properly such bug we should refactor the bot on a new structure, less string-dependent and more modular.
Too much for the aim of a basic multi language support.
=> fix: workaround for router's obfuscation

data/markdown/trasporto_urbano_unict.md
Aggiunta link orari navetta FCE; proseguio di #221, collegato a #217.
I hope I didn't mess anything 😅
=> Update trasporto_urbano_unict.md, parte 2

data/markdown/cloud.md
=> feat: add link to git catalogue uni notes

module/gitlab.py
Also added parsing exception.
Fixes https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/260
=> Notify admin on Gitlab exception raised getting groups

.gitignore, data/markdown/aule_studio.md, data/translations/en.yaml, data/translations/it.yaml, main.py, module/data/vars.py, tests/e2e/test_help.py
thanks [filippocampo98](https://github.com/filippocampo98)
closes https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/240
=> feat: implement aule studio

.github/workflows/telegram-bot.yml
closes https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/247
=> feat: Improve ci cd

.gitignore, data/markdown/faq.md
closes https://github.com/UNICT-DMI/Telegram-DMI-Bot/issues/265
related of https://github.com/UNICT-DMI/faq-dmi-bot/issues/9
=> doc: add reference to Ask DMI
